title: Nguyen Quoc Anh 
subtitle: Anh Q. Nguyen # Add your subtitle here
logo: /assets:img/headshot_circle2.png
description: >  # This is your short bio section
  This is a short bio about Nguyễn Quốc Anh. 
  Here you can talk about your interests,
  your work, what you're passionate about, or anything else you'd like to share.
  Keep it concise but informative.
show_downloads: false
theme: jekyll-theme-minimal
