title: Nguyen Quoc Anh 
logo: /assets:img/kyo.png
description: > 
     "Stress doesn’t come from hard work. Stress comes from not taking action over something that you can have some control over." - Jeff Bezos, 1996 
show_downloads: true
theme: jekyll-theme-minimal
