title: Nguyen Quoc Anh
logo: /assets:img/kyo.png
description: >
  - Publication Name: Anh Q. Nguyen
  
  - Role: Ambitious Data Scientist & Research Scholar at RMIT Vietnam
  
  - Specialization: Data Analytics & Machine Learning
  
  - Education: Pursuing B.Bus. in Economics & Finance, 100 CPE Credits in Data Science (NASBA)
  - Skills: Interdisciplinary Studies in Finance, Business Analysis, Data Science (CFA, BA, DS)
  - Research: Development of ML/DL models with Chaos Theory, Federated Learning, Advanced Encryption Techniques
  - Objective: Innovate in Algorithmic Trading & Data Security using Decentralised AI
theme: jekyll-theme-minimal
