title: Nguyen Quoc Anh 
subtitle: Anh Q. Nguyen # Add your subtitle here
logo: /assets:img/headshot_circle2.png
description: >  # This is your short bio section
  Publication name: Anh Q. Nguyen 
show_downloads: false
theme: jekyll-theme-minimal
