title: Nguyen Quoc Anh 
subtitle: Anh Q. Nguyen # Add your subtitle here
logo: /assets:img/kyo.png
description: >  # This is your short bio section
  bio
show_downloads: false
theme: jekyll-theme-minimal
